basic_settings:
  site_title: "David Angeles-Albores, Ph.D."
  favicon_image: "/assets/img/favicon.png"

header_settings:
  logo_image: "/assets/img/brand/white.png"
  mobile_logo_image: "/assets/img/brand/blue.png"
  theme: "dark"
  allow_transparent: "yes"

home_settings:
  theme: "landing"

blog_settings:
  theme: "basic"
  read_more: "yes"

menu_settings:
  menu_items:
    - title: "Home"
      url: "/"
    - title: "About Me"
      url: "/about"
    - title: "Portfolio"
      url: "/projects"
    - title: "Blog"
      url: "/blog"
    - title: "Contact"
      url: "/contact"

footer_settings:
  footer_tagline: "Â© 2026 David Angeles-Albores"

contact_settings:
  form_action: "https://formspree.io/davidangelesalbores@gmail.com"
  confirmation_url: "/thanks"
  email_subject: "Contact form submission"
  send_button_text: "Send Message"

social_settings:
  facebook_url: ""
  twitter_url: ""
  instagram_url: ""
  youtube_url: ""
  vimeo_url: ""
  pinterest_url: ""
  tumblr_url: ""
  dribbble_url: ""
  behance_url: ""
  github_url: "https://github.com/dangeles"
  reddit_url: ""
  linkedin_url: "https://www.linkedin.com/in/dangelesgenetics"

authors:
  david:
    name: David
    picture: /assets/img/faces/david.tiff

advanced_settings:
  google_analytics: G-ESQ24FE2J1
  analytics_code: G-ESQ24FE2J1
  header_js: 
  footer_js: 
